# Generated by Django 2.1.5 on 2019-03-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190330_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='task_status',
            field=models.SmallIntegerField(choices=[(0, 'initialized'), (1, 'success'), (2, 'failed'), (3, 'timeout')], default=0),
        ),
    ]
